name: Hello World

on:
  push:
    branches:
      - main
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo del mensaje
        run: echo "Hola Mundo!!!"
      - name: Muestra el contenido de la maquina.
        run: ls -la
  deploy_env:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo build --verbose
      - name: Build | Tests
        run: cargo test --verbose
